# Stage 1: build do Angular
FROM node:22 AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build


# Stage 2: servidor Nginx
FROM nginx:alpine
COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

